---
ovirt_engine_remote_db_port: 5432
ovirt_engine_remote_db_listen_address: '*'
ovirt_engine_db_name: 'engine'
ovirt_engine_db_user: 'engine'

ovirt_engine_remote_db: False
ovirt_engine_dwh_remote_db: False

ovirt_engine_dwh_db_name: 'ovirt_engine_history'
ovirt_engine_dwh_db_user: 'ovirt_engine_history'
