---
# example playbook for installing engines
# use with examples/inventory/install_engine.inv
- hosts: engine
  remote_user: root
  roles:
    - {role: ovirt-common}
    - {role: ovirt-engine-install-packages}
    - {role: ovirt-engine-setup}
