---
# health page
- name: check if ovirt-engine running (health page)
  uri:
    url: "http://{{ovirt_engine_hostname}}/ovirt-engine/services/health"
    status_code: 200
  register: ovirt_engine_status
  retries: 2
  delay: 5
  until: ovirt_engine_status|success
  ignore_errors: True

# copy answer file
- name: copy answerfile
  template:
    src: answerfile_{{ovirt_engine_answer_file_type}}.txt.j2
    dest: /tmp/answerfile.txt
    mode: 0644
    owner: root
    group: root

- name: run engine-setup with answerfile
  shell: 'engine-setup --config-append=/tmp/answerfile.txt'
  when: ovirt_engine_status|failed
