---
# cannot use module service, when service doesn't exists, it fail
# cannot use shell service & systemctl - service can be disabled, stopped -> many cases & different return codes
# in both cases, it will fail -> stderr message -> need ignore_errors
# TODO need refactoring - other way how to check ovirt-engine service
- name: check ovirt-engine service
  service:
    name: ovirt-engine
    state: running
  register: ovirt_engine_status
  ignore_errors: True

# copy answer file
- name: copy answerfile
  template:
    # TODO generate this varialbe from ovirt_engine_version and ovirt_engine_dwh
    src: answerfile_{{ovirt_engine_answer_file_type}}.txt.j2
    dest: /tmp/answer_file.txt
    mode: 0644
    owner: root
    group: root

- name: run engine-setup with answerfile
  shell: 'engine-setup --config-append=/tmp/answer_file.txt'
  when: ovirt_engine_status|failed
  tags:
    -skip_ansible_lint

- name: check state of database
  service:
    name: postgresql
    state: running

- name: check state of engine
  service:
    name: ovirt-engine
    state: running

- name: restart of ovirt-engine service
  service:
    name: ovirt-engine
    state: restarted

- name: check health status of page
  uri:
    url: "http://{{ovirt_engine_hostname}}/ovirt-engine/services/health"
    status_code: 200
  register: health_page
  retries: 12
  delay: 10
  until: health_page|success
